"""
Solution data model.

Owner: [ASSIGN TEAMMATE]
"""

from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class SolutionSource(str, Enum):
    """Source of the solution."""

    EXISTING = "existing"  # Found in RAG context
    NOVEL = "novel"  # Generated by proposers


class SolutionStatus(str, Enum):
    """Status of the solution."""

    DRAFT = "draft"
    PENDING_JUDGMENT = "pending_judgment"
    APPROVED = "approved"
    REJECTED = "rejected"


class Solution(BaseModel):
    """
    A solution to an atomic requirement.

    Attributes:
        id: Unique identifier
        requirement_id: The atomic requirement this solves
        content: The solution text
        reasoning_chain: Steps from Tree of Thoughts reasoning
        source: Whether this was found or generated
        confidence: Confidence score (0-1)
        status: Current status
        judge_votes: Voting results from solution judges
        judge_feedback: Feedback from judges
    """

    id: UUID = Field(default_factory=uuid4)
    requirement_id: UUID
    content: str
    reasoning_chain: list[str] = Field(default_factory=list)
    source: SolutionSource = SolutionSource.NOVEL
    confidence: float = Field(0.0, ge=0.0, le=1.0)
    status: SolutionStatus = SolutionStatus.DRAFT

    # Judge results
    judge_votes: list[bool] = Field(default_factory=list)
    judge_scores: list[float] = Field(default_factory=list)
    judge_feedback: list[str] = Field(default_factory=list)
